# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: pg
  pool: 5
  timeout: 5000

development:
   adapter: mysql2
   database: development
   username: root
   password: root
   host: localhost

test:
   adapter: pg
   database: library_test
   username: root
   password: root
   host: localhost

production:
   adapter: pg
   database: library_production
   username: root
   password: root
   host: localhost